name: Run command in cmd

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:  
        dotnet-version: '3.1'
    - uses: actions/checkout@v2
    - run: cmd /c "dotnet cake"