name: Run command in cmd

on: push

jobs:
    install-unity:


    build:
        runs-on: windows-latest
    steps:
        - name: Setup .NET Core 
            uses: actions/setup-dotnet@v1
            with: 
            dotnet-version: '3.1' # Версия .NET Core SDK
        - name: Checkout code
        - uses: actions/checkout@v2
        - name: Run command
            run: | 
            cmd /c "dotnet cake


            # НАДА:
                # Сделать сохранение чувствительных данных в github secrets
                # Сделать сохранение сессии телеграмма в github secrets