name: Run command in cmd

on: push

jobs:
  build:
    runs-on: windows-latest
    environment: "Generic Web GL Build Cake Environment"
    steps:
    - uses: actions/setup-dotnet@v1
      with:  
        dotnet-version: '6.0'
    - uses: actions/checkout@v2
    - run: "dotnet new tool-manifest"
    - run: "dotnet tool install Cake.Tool --version 3.0.0"
    - run: >
        dotnet cake
         --Telegram_ApiId=${{secrets.TELEGRAM_API_ID}}
         --Telegram_ApiHash=${{secrets.TELEGRAM_API_HASH}}
         --Telegram_PhoneNumber=${{secrets.PHONE_NUMBER}}
         --Telegram_ChatId=${{secrets.TELEGRAM_CHAT_ID}}
         --Ftp_Host=${{secrets.FTP_HOST}}
         --Ftp_Login=${{secrets.FTP_LOGIN}}
         --Ftp_Password=${{secrets.FTP_PASSWORD}}
         --Telegram_SessionPath=D:\MyTelegramSession.session