name: Run command in cmd

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:  
        dotnet-version: '6.0'
    - uses: actions/checkout@v2
    - run: "dotnet new tool-manifest"
    - run: "dotnet tool install Cake.Tool --version 3.0.0"
    - run: "dotnet cake"